export const EYE = {
  'EYES.HAZEL.DARK': {
    id: 'EYES.HAZEL.DARK',
    type: 'color',
    category: 'EYES',
    group: 'HAZEL',
    name: 'DARK',
    value: '#42210a',
    rate: 16,
  },
  'EYES.HAZEL.MEDIUM': {
    id: 'EYES.HAZEL.MEDIUM',
    type: 'color',
    category: 'EYES',
    group: 'HAZEL',
    name: 'MEDIUM',
    value: '#5e3a21',
    rate: 12,
  },
  'EYES.HAZEL.LIGHT': {
    id: 'EYES.HAZEL.LIGHT',
    type: 'color',
    category: 'EYES',
    group: 'HAZEL',
    name: 'LIGHT',
    value: '#6e4822',
    rate: 8,
  },
  'EYES.HAZEL.RED': {
    id: 'EYES.HAZEL.RED',
    type: 'color',
    category: 'EYES',
    group: 'HAZEL',
    name: 'RED',
    value: '#693026',
    rate: 4,
  },
  'EYES.BLUE.DARK': {
    id: 'EYES.BLUE.DARK',
    type: 'color',
    category: 'EYES',
    group: 'BLUE',
    name: 'DARK',
    value: '#294d7a',
    rate: 9,
  },
  'EYES.BLUE.SAPPHIRE': {
    id: 'EYES.BLUE.SAPPHIRE',
    type: 'color',
    category: 'EYES',
    group: 'BLUE',
    name: 'SAPPHIRE',
    value: '#016683',
    rate: 3,
  },
  'EYES.BLUE.DEEP': {
    id: 'EYES.BLUE.DEEP',
    type: 'color',
    category: 'EYES',
    group: 'BLUE',
    name: 'DEEP',
    value: '#3f76bb',
    rate: 12,
  },
  'EYES.BLUE.AQUA': {
    id: 'EYES.BLUE.AQUA',
    type: 'color',
    category: 'EYES',
    group: 'BLUE',
    name: 'AQUA',
    value: '#6fcbd6',
    rate: 6,
  },
  'EYES.GREEN.DARK': {
    id: 'EYES.GREEN.DARK',
    type: 'color',
    category: 'EYES',
    group: 'GREEN',
    name: 'DARK',
    value: '#1b694a',
    rate: 4,
  },
  'EYES.GREEN.JADE': {
    id: 'EYES.GREEN.JADE',
    type: 'color',
    category: 'EYES',
    group: 'GREEN',
    name: 'JADE',
    value: '#018376',
    rate: 2,
  },
  'EYES.GREEN.EMERALD': {
    id: 'EYES.GREEN.EMERALD',
    type: 'color',
    category: 'EYES',
    group: 'GREEN',
    name: 'EMERALD',
    value: '#31c482',
    rate: 8,
  },
  'EYES.GREEN.NAME': {
    id: 'EYES.GREEN.NAME',
    type: 'color',
    category: 'EYES',
    group: 'GREEN',
    name: 'NAME',
    value: '#3ab44a',
    rate: 6,
  },
  'EYES.BLACK.PURE': {
    id: 'EYES.BLACK.PURE',
    type: 'color',
    category: 'EYES',
    group: 'BLACK',
    name: 'PURE',
    value: '#000000',
    rate: 3,
  },
  'EYES.BLACK.DARK': {
    id: 'EYES.BLACK.DARK',
    type: 'color',
    category: 'EYES',
    group: 'BLACK',
    name: 'DARK',
    value: '#000000',
    rate: 4,
  },
  'EYES.BLACK.GREY': {
    id: 'EYES.BLACK.GREY',
    type: 'color',
    category: 'EYES',
    group: 'BLACK',
    name: 'GREY',
    value: '#44453e',
    rate: 2,
  },
  'EYES.BLACK.BLIND': {
    id: 'EYES.BLACK.BLIND',
    type: 'color',
    category: 'EYES',
    group: 'BLACK',
    name: 'BLIND',
    value: '#c0beb9',
    rate: 1,
  },
};
