export const FUR = {
  'FUR.CARAMEL.DARK': {
    id: 'FUR.CARAMEL.DARK',
    type: 'color',
    category: 'FUR',
    group: 'CARAMEL',
    name: 'DARK',
    value: '#a5711f',
    rate: 16,
  },
  'FUR.CARAMEL.MEDIUM': {
    id: 'FUR.CARAMEL.MEDIUM',
    type: 'color',
    category: 'FUR',
    group: 'CARAMEL',
    name: 'MEDIUM',
    value: '#c28b40',
    rate: 8,
  },
  'FUR.CARAMEL.LIGHT': {
    id: 'FUR.CARAMEL.LIGHT',
    type: 'color',
    category: 'FUR',
    group: 'CARAMEL',
    name: 'LIGHT',
    value: '#c49a48',
    rate: 12,
  },
  'FUR.CARAMEL.MUTED': {
    id: 'FUR.CARAMEL.MUTED',
    type: 'color',
    category: 'FUR',
    group: 'CARAMEL',
    name: 'MUTED',
    value: '#b2915d',
    rate: 4,
  },
  'FUR.GOLD.DARK': {
    id: 'FUR.GOLD.DARK',
    type: 'color',
    category: 'FUR',
    group: 'GOLD',
    name: 'DARK',
    value: '#977725',
    rate: 9,
  },
  'FUR.GOLD.MEDIUM': {
    id: 'FUR.GOLD.MEDIUM',
    type: 'color',
    category: 'FUR',
    group: 'GOLD',
    name: 'MEDIUM',
    value: '#ab8925',
    rate: 12,
  },
  'FUR.GOLD.BRIGHT': {
    id: 'FUR.GOLD.BRIGHT',
    type: 'color',
    category: 'FUR',
    group: 'GOLD',
    name: 'BRIGHT',
    value: '#d3b437',
    rate: 6,
  },
  'FUR.GOLD.LIGHT': {
    id: 'FUR.GOLD.LIGHT',
    type: 'color',
    category: 'FUR',
    group: 'GOLD',
    name: 'LIGHT',
    value: '#d9c350',
    rate: 3,
  },
  'FUR.BROWN.DARK': {
    id: 'FUR.BROWN.DARK',
    type: 'color',
    category: 'FUR',
    group: 'BROWN',
    name: 'DARK',
    value: '#574639',
    rate: 4,
  },
  'FUR.BROWN.MEDIUM': {
    id: 'FUR.BROWN.MEDIUM',
    type: 'color',
    category: 'FUR',
    group: 'BROWN',
    name: 'MEDIUM',
    value: '#7b623e',
    rate: 6,
  },
  'FUR.BROWN.LIGHT': {
    id: 'FUR.BROWN.LIGHT',
    type: 'color',
    category: 'FUR',
    group: 'BROWN',
    name: 'LIGHT',
    value: '#8c754a',
    rate: 8,
  },
  'FUR.BROWN.MUTED': {
    id: 'FUR.BROWN.MUTED',
    type: 'color',
    category: 'FUR',
    group: 'BROWN',
    name: 'MUTED',
    value: '#a3967a',
    rate: 2,
  },
  'FUR.RED.DARK': {
    id: 'FUR.RED.DARK',
    type: 'color',
    category: 'FUR',
    group: 'RED',
    name: 'DARK',
    value: '#8b4935',
    rate: 2,
  },
  'FUR.RED.BRIGHT': {
    id: 'FUR.RED.BRIGHT',
    type: 'color',
    category: 'FUR',
    group: 'RED',
    name: 'BRIGHT',
    value: '#bf4c30',
    rate: 1,
  },
  'FUR.RED.MEDIUM': {
    id: 'FUR.RED.MEDIUM',
    type: 'color',
    category: 'FUR',
    group: 'RED',
    name: 'MEDIUM',
    value: '#bf6c30',
    rate: 4,
  },
  'FUR.RED.MUTED': {
    id: 'FUR.RED.MUTED',
    type: 'color',
    category: 'FUR',
    group: 'RED',
    name: 'MUTED',
    value: '#c18042',
    rate: 3,
  },
};
