export const HAIR = {
  'HAIR.BRUNETTE.DARK': {
    id: 'HAIR.BRUNETTE.DARK',
    type: 'color',
    category: 'HAIR',
    group: 'BRUNETTE',
    name: 'DARK',
    value: '#3b2110',
    rate: 16,
  },
  'HAIR.BRUNETTE.MEDIUM': {
    id: 'HAIR.BRUNETTE.MEDIUM',
    type: 'color',
    category: 'HAIR',
    group: 'BRUNETTE',
    name: 'MEDIUM',
    value: '#603813',
    rate: 12,
  },
  'HAIR.BRUNETTE.LIGHT': {
    id: 'HAIR.BRUNETTE.LIGHT',
    type: 'color',
    category: 'HAIR',
    group: 'BRUNETTE',
    name: 'LIGHT',
    value: '#754c28',
    rate: 8,
  },
  'HAIR.BRUNETTE.ORANGE': {
    id: 'HAIR.BRUNETTE.ORANGE',
    type: 'color',
    category: 'HAIR',
    group: 'BRUNETTE',
    name: 'ORANGE',
    value: '#ffbe4d',
    rate: 4,
  },
  'HAIR.BLACK.PURE': {
    id: 'HAIR.BLACK.PURE',
    type: 'color',
    category: 'HAIR',
    group: 'BLACK',
    name: 'PURE',
    value: '#140d08',
    rate: 9,
  },
  'HAIR.BLACK.GRAY': {
    id: 'HAIR.BLACK.GRAY',
    type: 'color',
    category: 'HAIR',
    group: 'BLACK',
    name: 'GRAY',
    value: '#231f20',
    rate: 3,
  },
  'HAIR.BLACK.CHOCOLATE': {
    id: 'HAIR.BLACK.CHOCOLATE',
    type: 'color',
    category: 'HAIR',
    group: 'BLACK',
    name: 'CHOCOLATE',
    value: '#24180a',
    rate: 12,
  },
  'HAIR.BLACK.OLIVE': {
    id: 'HAIR.BLACK.OLIVE',
    type: 'color',
    category: 'HAIR',
    group: 'BLACK',
    name: 'OLIVE',
    value: '#2b230e',
    rate: 6,
  },
  'HAIR.BLOND.GOLDEN': {
    id: 'HAIR.BLOND.GOLDEN',
    type: 'color',
    category: 'HAIR',
    group: 'BLOND',
    name: 'GOLDEN',
    value: '#d3a40f',
    rate: 8,
  },
  'HAIR.BLOND.BRIGHT': {
    id: 'HAIR.BLOND.BRIGHT',
    type: 'color',
    category: 'HAIR',
    group: 'BLOND',
    name: 'BRIGHT',
    value: '#fff64d',
    rate: 4,
  },
  'HAIR.BLOND.DESERT': {
    id: 'HAIR.BLOND.DESERT',
    type: 'color',
    category: 'HAIR',
    group: 'BLOND',
    name: 'DESERT',
    value: '#d3bd5e',
    rate: 2,
  },
  'HAIR.BLOND.DARK': {
    id: 'HAIR.BLOND.DARK',
    type: 'color',
    category: 'HAIR',
    group: 'BLOND',
    name: 'DARK',
    value: '#705a17',
    rate: 6,
  },
  'HAIR.RED.GINGER': {
    id: 'HAIR.RED.GINGER',
    type: 'color',
    category: 'HAIR',
    group: 'RED',
    name: 'GINGER',
    value: '#e33e3d',
    rate: 3,
  },
  'HAIR.RED.BURGUNDY': {
    id: 'HAIR.RED.BURGUNDY',
    type: 'color',
    category: 'HAIR',
    group: 'RED',
    name: 'BURGUNDY',
    value: '#581600',
    rate: 4,
  },
  'HAIR.RED.CARROT': {
    id: 'HAIR.RED.CARROT',
    type: 'color',
    category: 'HAIR',
    group: 'RED',
    name: 'CARROT',
    value: '#e3764a',
    rate: 2,
  },
  'HAIR.RED.WHITE': {
    id: 'HAIR.RED.WHITE',
    type: 'color',
    category: 'HAIR',
    group: 'RED',
    name: 'WHITE',
    value: '#c6bec8',
    rate: 1,
  },
};
