export const NOSE = {
  'NOSE.BLACK.PURE': {
    id: 'NOSE.BLACK.PURE',
    type: 'color',
    category: 'NOSE',
    group: 'BLACK',
    name: 'PURE',
    value: '#140e08',
    rate: 8,
  },
  'NOSE.BLACK.MUD': {
    id: 'NOSE.BLACK.MUD',
    type: 'color',
    category: 'NOSE',
    group: 'BLACK',
    name: 'MUD',
    value: '#2b230e',
    rate: 12,
  },
  'NOSE.BLACK.COFFEE': {
    id: 'NOSE.BLACK.COFFEE',
    type: 'color',
    category: 'NOSE',
    group: 'BLACK',
    name: 'COFFEE',
    value: '#37250c',
    rate: 20,
  },
  'NOSE.BROWN.DARK': {
    id: 'NOSE.BROWN.DARK',
    type: 'color',
    category: 'NOSE',
    group: 'BROWN',
    name: 'DARK',
    value: '#522906',
    rate: 15,
  },
  'NOSE.BROWN.CARAMEL': {
    id: 'NOSE.BROWN.CARAMEL',
    type: 'color',
    category: 'NOSE',
    group: 'BROWN',
    name: 'CARAMEL',
    value: '#7a4f18',
    rate: 9,
  },
  'NOSE.BROWN.BRONZE': {
    id: 'NOSE.BROWN.BRONZE',
    type: 'color',
    category: 'NOSE',
    group: 'BROWN',
    name: 'BRONZE',
    value: '#725f10',
    rate: 6,
  },
  'NOSE.RED.DARK': {
    id: 'NOSE.RED.DARK',
    type: 'color',
    category: 'NOSE',
    group: 'RED',
    name: 'DARK',
    value: '#9c3930',
    rate: 6,
  },
  'NOSE.RED.BRIGHT': {
    id: 'NOSE.RED.BRIGHT',
    type: 'color',
    category: 'NOSE',
    group: 'RED',
    name: 'BRIGHT',
    value: '#cc3f3f',
    rate: 4,
  },
  'NOSE.RED.MUTED': {
    id: 'NOSE.RED.MUTED',
    type: 'color',
    category: 'NOSE',
    group: 'RED',
    name: 'MUTED',
    value: '#b46838',
    rate: 12,
  },
  'NOSE.ALBINO.PINK': {
    id: 'NOSE.ALBINO.PINK',
    type: 'color',
    category: 'NOSE',
    group: 'ALBINO',
    name: 'PINK',
    value: '#efdfd5',
    rate: 5,
  },
  'NOSE.ALBINO.BEIGE': {
    id: 'NOSE.ALBINO.BEIGE',
    type: 'color',
    category: 'NOSE',
    group: 'ALBINO',
    name: 'BEIGE',
    value: '#eeefd5',
    rate: 2,
  },
  'NOSE.ALBINO.GRAY': {
    id: 'NOSE.ALBINO.GRAY',
    type: 'color',
    category: 'NOSE',
    group: 'ALBINO',
    name: 'GRAY',
    value: '#e6e4db',
    rate: 3,
  },
};
