export const SNOUT = {
  'SNOUT.ORANGE.REGULAR': {
    id: 'SNOUT.ORANGE.REGULAR',
    type: 'color',
    category: 'SNOUT',
    group: 'ORANGE',
    name: 'REGULAR',
    value: '#f2d4b1',
    rate: 40,
  },
  'SNOUT.CREAM.REGULAR': {
    id: 'SNOUT.CREAM.REGULAR',
    type: 'color',
    category: 'SNOUT',
    group: 'CREAM',
    name: 'REGULAR',
    value: '#f6ebb4',
    rate: 30,
  },
  'SNOUT.DUST.REGULAR': {
    id: 'SNOUT.DUST.REGULAR',
    type: 'color',
    category: 'SNOUT',
    group: 'DUST',
    name: 'REGULAR',
    value: '#dacdbd',
    rate: 20,
  },
  'SNOUT.SALMON.REGULAR': {
    id: 'SNOUT.SALMON.REGULAR',
    type: 'color',
    category: 'SNOUT',
    group: 'SALMON',
    name: 'REGULAR',
    value: '#f5dccb',
    rate: 10,
  },
};
